chore: fix verify_library_generation.yaml for forks (#2716)
PRs opened by renovate-bot are failing `verify_library_generation`
because renovate-bot opens PRs from a fork rather than main.

For instance https://github.com/googleapis/sdk-platform-java/pull/2657
is failing:

```
env:
    base_ref: main
    head_ref: renovate/markupsafe-2.x
+ git checkout main
Previous HEAD position was d84e6072d Merge 645951c0497bf9cdb42e6323cd90a08d77a1926a into 766646a9e0bed6c8e804eb1e6ab4d[13](https://github.com/googleapis/sdk-platform-java/actions/runs/8914757209/job/24482995077?pr=2657#step:3:13)3d1465dca
Switched to a new branch 'main'
branch 'main' set up to track 'origin/main'.
+ git checkout renovate/markupsafe-2.x
error: pathspec 'renovate/markupsafe-2.x' did not match any file(s) known to git
```
This updates the yaml file to explicitly fetch specific branches which
should fix the issue.

---------

Co-authored-by: Joe Wang <106995533+JoeWang1127@users.noreply.github.com>