fix: `BaseApiTracer` to noop on attemptFailed via overloaded method call (#3016)
Fixes https://github.com/googleapis/sdk-platform-java/issues/3015
Fixes https://github.com/googleapis/sdk-platform-java/issues/3014

Gax tracing internally works with `attemptFailedDuration`, which
defaults to a no-op. Downstream libraries use `attemptFailed`, which has
a custom behavior. What happens when an attempt-failed event occurs is
that `attemptFailedDuration` is called instead (in favor of using
java.time methods internally). This fix makes `attemptFailedDuration`'s
behavior to delegate the logic to `attemptFailed`.

The downstreams will keep failing because the repos haven't got adapted
to the new change in gax. See the follow ups below.

### Fixes in `java-spanner`

![image](https://github.com/googleapis/sdk-platform-java/assets/22083784/85e50341-fe8b-46c8-9743-8de1ca300058)

### Fixes in `java-bigtable`

![image](https://github.com/googleapis/sdk-platform-java/assets/22083784/026af401-1607-4465-abd5-1ee5ddc353d0)


### Follow ups in `java-bigtable`
More failures in java-bigtable to be addressed in that repo:
```
Error:    BigtableTableAdminSettingsTest.testToString:175 expected to contain: totalTimeout=PT13H32M
but was            : BigtableTableAdminSettings{projectId=our-project-85, instanceId=our-instance-06, 
...
```

Fixed in https://github.com/googleapis/java-bigtable/pull/2274

### Follow ups in `java-spanner`
```
Error:  Failures: 
Error:    CompositeTracerTest.testMethodsOverrideMetricsTracer:238 Method not found in compositeTracerMethods: public void com.google.api.gax.tracing.MetricsTracer.attemptFailedDuration(java.lang.Throwable,java.time.Duration)
```
Fixed in https://github.com/googleapis/java-spanner/pull/3200